# Generated by Django 6.1.1 on 2026-09-22 06:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_and_logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_reason', models.CharField(choices=[('SPOILED_PRODUCE', 'Spoiled or Rotten Produce'), ('WEIGHT_SHORTFALL', 'Weight Shortfall / Discrepancy'), ('QUALITY_MISREPRESENTATION', 'Quality Misrepresentation / Lower Grade'), ('TRANSIT_DAMAGE', 'Transit Mishandling or Physical Damage'), ('INCORRECT_ITEM', 'Incorrect Produce Delivered')], default='SPOILED_PRODUCE', max_length=30)),
                ('video_proof_url', models.URLField(help_text='Mandatory continuous unboxing video proof link (e.g. S3/Supabase Storage/Cloudinary URL)')),
                ('unboxing_video_file', models.FileField(blank=True, null=True, upload_to='dispute_videos/')),
                ('description', models.TextField(help_text='Detailed description of the issue observed')),
                ('received_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight measured upon unboxing (for WEIGHT_SHORTFALL claims)', max_digits=10, null=True)),
                ('fault_party', models.CharField(choices=[('FARMER', 'Farmer Fault'), ('LOGISTICS', 'Logistics Carrier Fault'), ('CONSUMER', 'Consumer Error'), ('SPLIT', 'Shared Fault'), ('PENDING_ASSESSMENT', 'Pending Assessment')], default='PENDING_ASSESSMENT', max_length=30)),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('farmer_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted (Under Video Verification)'), ('INVESTIGATING', 'Fault Matrix Evaluation in Progress'), ('RESOLVED_FULL_REFUND', 'Resolved: Full Refund to Consumer'), ('RESOLVED_PARTIAL_REFUND', 'Resolved: Partial Refund Applied'), ('RESOLVED_REJECTED', 'Resolved: Claim Rejected (Escrow Released to Farmer)')], db_index=True, default='SUBMITTED', max_length=30)),
                ('evaluation_notes', models.TextField(blank=True)),
                ('carrier_insurance_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='orders_and_logistics.order')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
