# Generated by Django 6.1.1 on 2026-09-22 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('AGRISTACK', 'AgriStack ID (State DB)'), ('KCC', 'Kisan Credit Card (Bank / C-DAC)'), ('BHULEKH', 'Bhulekh Record (DILRMP Land Registry)')], default='AGRISTACK', max_length=20)),
                ('agristack_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('kcc_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('land_record_khata', models.CharField(blank=True, max_length=50, null=True)),
                ('land_khasra_plot', models.CharField(blank=True, max_length=50, null=True)),
                ('land_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('land_holding_acres', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_badge_id', models.CharField(blank=True, max_length=64, null=True)),
                ('verification_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
