# Generated by Django 6.1.1 on 2026-09-22 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FINANCIAL_SUPPORT', 'Direct Financial Support (PM-KISAN)'), ('DIGITIZATION', 'Digital Registries & Identity (AgriStack)'), ('INSURANCE', 'Crop Insurance & Risk Mitigation (PMFBY)'), ('CREDIT', 'Institutional Credit (KCC / JanSamarth)'), ('SUBSIDY', 'Inputs, Soil & Irrigation Subsidies')], default='FINANCIAL_SUPPORT', max_length=30)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits_summary', models.TextField()),
                ('portal_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp Business Bot'), ('WEB', 'Web / App Portal')], default='WHATSAPP', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BOT_RESOLVED', 'Resolved by Bot AutoReply'), ('ESCALATED_AGENT', 'Escalated to Support Officer'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('conversation_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
