# Generated by Django 6.1.1 on 2026-09-22 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentMSP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('GRAINS', 'Cereals & Grains'), ('PULSES', 'Pulses & Legumes'), ('OILSEEDS', 'Oilseeds'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('COMMERCIAL', 'Commercial & Cash Crops')], default='GRAINS', max_length=20)),
                ('msp_per_quintal', models.DecimalField(decimal_places=2, help_text='Government MSP in INR per quintal (100 kg)', max_digits=10)),
                ('msp_per_kg', models.DecimalField(decimal_places=2, help_text='Government MSP in INR per kg (msp_per_quintal / 100)', max_digits=10)),
                ('marketing_season', models.CharField(default='2025-2026', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('GRAINS', 'Cereals & Grains'), ('PULSES', 'Pulses & Legumes'), ('OILSEEDS', 'Oilseeds'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('COMMERCIAL', 'Commercial & Cash Crops')], default='GRAINS', max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity_available_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msp_floor_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('shelf_life_days', models.PositiveIntegerField(default=14)),
                ('is_organic', models.BooleanField(default=False)),
                ('farm_pincode', models.CharField(db_index=True, max_length=10)),
                ('farm_district', models.CharField(blank=True, max_length=100)),
                ('farm_state', models.CharField(blank=True, max_length=100)),
                ('farm_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('farm_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1500937386664-56d1dfef3854')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
