# Generated by Django 6.1.1 on 2026-09-22 06:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produce_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('logistics_partner', models.CharField(choices=[('DELHIVERY', 'Delhivery Surface & Express'), ('PORTER', 'Porter Intra-City Mini Truck'), ('DIRECT_PICKUP', 'Direct Farm Pickup')], default='DELHIVERY', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_address', models.TextField()),
                ('buyer_pincode', models.CharField(max_length=10)),
                ('buyer_phone', models.CharField(max_length=15)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('ESCROW_FUNDED', 'Escrow Funded (Funds Locked)'), ('DISPATCHED', 'Dispatched by Farmer'), ('IN_TRANSIT', 'In Transit (Logistics Courier)'), ('DELIVERED', 'Delivered to Customer'), ('COMPLETED', 'Completed (Funds Released to Farmer)'), ('DISPUTED', 'Disputed (Funds Frozen in Escrow)'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_orders', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.productlisting')),
            ],
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='TAZAPAY', max_length=50)),
                ('escrow_reference_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('LOCKED_IN_ESCROW', 'Funds Locked in Escrow'), ('RELEASED_TO_FARMER', 'Released to Farmer'), ('REFUNDED_TO_BUYER', 'Refunded to Buyer'), ('PARTIALLY_REFUNDED', 'Partially Refunded via Fault Matrix')], default='INITIATED', max_length=30)),
                ('buyer_paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders_and_logistics.order')),
            ],
        ),
    ]
